modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/DbExecutor.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/sqlquery/SqlQueryEnrichmentIntegrationTest.scala
=> Common: Skip sql enrichment on null values as placeholders (close #291)

project/BuildSettings.scala
=> Beam: Bump k8s-dataflow to 0.2.0

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/YauaaEnrichment.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/YauaaEnrichmentSpec.scala
=> Remove __SyntaxError__ from YAUAA context (close #414)

modules/stream/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/SnowplowTracking.scala
=> Stream: Rename 'internal' to 'interval' in app_heartbeat (close #410)

modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/EnrichSpec.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/enrichments/ApiRequestEnrichmentSpec.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/enrichments/IabEnrichmentSpec.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/test/HttpServer.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/test/package.scala
=> fix flaky AssetsSpec test

modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Assets.scala, modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Environment.scala, modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Run.scala, modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/io/Clients.scala, modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/S3Client.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/enrich/pubsub/GcsClient.scala, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/enrich/pubsub/Main.scala
=> Better asset download

build.sbt, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/EventGenEtlPipelineSpec.scala, project/Dependencies.scala
Add an event generator test for ETL pipeline (close #535)
This is a continuation of https://github.com/snowplow/enrich/pull/520
=> Add an event generator test for ETL pipeline (close #535)

modules/kinesis/src/it/resources/config.hocon, modules/kinesis/src/it/scala/com/snowplowanalytics/snowplow/enrich/kinesis/test/Resources.scala
Details at https://github.com/snowplow/enrich/issues/599
=> enrich-kinesis: use flatMap for the resources in the integration test

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/EtlPipeline.scala, modules/stream/common/src/main/scala/com.snowplowanalytics.snowplow.enrich.stream/sources/Source.scala
=> Stream Enrich: Fix the enrichment order (close #662)

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/HttpClient.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/HttpClientSpec.scala
See https://github.com/snowplow/enrich/issues/660
=> Common: Get HttpClient to Set Authorization header and Content-Type (close #660)

config/config.pubsub.extended.hocon, modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/io.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ConfigFileSpec.scala, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ParsedConfigsSpec.scala, modules/pubsub/src/main/resources/application.conf, modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/enrich/pubsub/Source.scala
=> Add Flow Control to PubSub consumer

.github/workflows/ci.yml, build.sbt, integration-tests/enrich-kafka/config/enrich-kafka.hocon, integration-tests/enrich-kafka/config/enrichments/yauaa_enrichment_config.json, integration-tests/enrich-kafka/config/iglu_resolver.json, integration-tests/enrich-kafka/docker-compose.yml, modules/kafka/src/it/scala/com/snowplowanalytics/snowplow/enrich/kafka/test/CollectorPayloadGen.scala, modules/kafka/src/it/scala/com/snowplowanalytics/snowplow/enrich/kafka/test/EnrichKafkaSpec.scala
tested on localhost successfully
collector payload generation is a copy-paste from `enrich-kinesis/it`
=> Add integration test of enrich-kafka

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/SendgridAdapter.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/adapters/registry/SendgridAdapterSpec.scala
=> common: remove duplicates from Sendgrid adapter payload

modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/io/FileSystem.scala
=> common-fs2: fix env var substitution for JSON files (close #753)

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/DbExecutor.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/SqlQueryEnrichment.scala, modules/kinesis/src/it/scala/com/snowplowanalytics/snowplow/enrich/kinesis/EnrichKinesisSpec.scala
=> SQL enrichment: put getConnection in Blocker

config/enrichments/api_request_enrichment_config.json, config/enrichments/sql_query_enrichment_config.json, modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/enrichments/ApiRequestEnrichmentSpec.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/EnrichmentConf.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/apirequest/ApiRequestEnrichment.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/CreateSqlQueryEnrichment.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/SqlQueryEnrichment.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/ApiRequestEnrichmentSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/HttpApiSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/InputSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/sqlquery/SqlQueryEnrichmentIntegrationTest.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/sqlquery/SqlQueryEnrichmentSpec.scala
Changes in the iglu central schemas - https://github.com/snowplow/iglu-central/pull/1273
=> Ignore API/SQL enrichments on error

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/JavascriptScriptEnrichment.scala, project/BuildSettings.scala
=> JS enrichment as IIFE

config/enrichments/cross_navigation_config.json, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentRegistry.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/CrossNavigationEnrichment.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/EnrichmentConf.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/web/PageEnrichments.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/CrossNavigationEnrichmentSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/EnrichmentConfigsSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/web/ParseCrossDomainSpec.scala
Continuation of https://github.com/snowplow/enrich/pull/821
Waiting for [necessary schemas to be released first](https://github.com/snowplow/iglu-central/pull/1368).
=> Add Cross Navigation Enrichment

modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentRegistrySpec.scala
This PR adds a few new test cases for multiple js enrichments.
=> Tests for Multiple javascript enrichments

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/EnrichmentConf.scala, modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/JavascriptScriptEnrichment.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentRegistrySpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/EnrichmentConfigsSpec.scala, modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/JavascriptScriptEnrichmentSpec.scala, project/BuildSettings.scala
Reopened this PR: https://github.com/snowplow/enrich/pull/840
Before merging this PR, new version of JS enrichment schema needs to be released. The PR for that schema is [here](https://github.com/snowplow/iglu-central/pull/1369).
=> Allow passing an object of parameters to the JS enrichment

modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/Rdbms.scala, modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/enrich/kafka/ConfigSpec.scala, modules/kinesis/src/test/scala/com/snowplowanalytics/snowplow/enrich/kinesis/ConfigSpec.scala, project/Dependencies.scala
=> Replace mysql client with mariadb client

.github/workflows/release.yml, .github/workflows/test.yml
This PR adds sbt installation to github workflows.
=> Install sbt in github actions
