- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/DbExecutor.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/SqlQueryEnrichment.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/sqlquery/SqlQueryEnrichmentIntegrationTest.scala
This actually make the enrichment to be skipped, the previous one just fixed the one function.
> Skip the SQL enrichment on null placeholders

- .github/workflows/test.yml
- build.sbt
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/AdapterRegistry.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/Adapter.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/adapters/registry/IgluAdapter.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/CollectorPayload.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/loaders/ThriftLoader.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/loaders/CollectorPayloadSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/loaders/ThriftLoaderSpec.scala
- project/BuildSettings.scala
- project/Dependencies.scala
> Common: add toThrift and toRaw methods to CollectorPayload (close #345)

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/CirceUtils.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/JsonPath.scala
- modules/common/src/main/scala/io/circe/jackson/enrich/CirceJsonDeserializer.scala
- modules/common/src/main/scala/io/circe/jackson/enrich/CirceJsonModule.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/ValidatorSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/utils/JsonPathSpec.scala
This PR introduces a new package `io.circe.jackson.enrich` which contains a custom deserialization logic since `circe-jackson`'s deserializer converts a `Long` to `JsonBigDecimal`, which results in `number found, integer expected` enrichment failures.
TO DO
> Common: fix API Request Enrichment output deserialization

- config/config.fs2.hocon.sample
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/Environment.scala
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/Main.scala
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/config/ConfigFile.scala
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/config/io.scala
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/io/Metrics.scala
- modules/fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/fs2/io/StatsDReporter.scala
- modules/fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/fs2/config/ConfigFileSpec.scala
- modules/fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/fs2/io/StatsDReporterSpec.scala
- modules/fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/fs2/test/Counter.scala
- modules/fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/fs2/test/TestEnvironment.scala
This the re-worked version.  We no longer use a 3rd party statsd client, but rather implement the statsd protocol ourselves.  This is because I could not find a 3rd party client that respected DNS changes during a long-running process.
Here, I call `InetAddress.getByName()` every time I want to send metrics.  This gives the JVM opportunity to re-query the DNS server.  The JVM will respect the ttl on DNS records, but otherwise will cache the result of a DNS lookup.
> Stream FS2: StatsD reporter for metrics (close #421)

- modules/bench/src/test/scala/com.snowplowanalytics.snowplow.enrich.bench/EnrichBench.scala
- modules/bench/src/test/scala/com.snowplowanalytics.snowplow.enrich.bench/EtlPipelineBench.scala
- modules/bench/src/test/scala/com.snowplowanalytics.snowplow.enrich.bench/ThriftLoaderBench.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/outputs/EnrichedEvent.scala
- modules/common/src/test/resources/iglu-schemas/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala
Enrichment uses the atomic event [schema](https://raw.githubusercontent.com/snowplow/iglu-central/master/schemas/com.snowplowanalytics.snowplow/atomic/jsonschema/1-0-0) for shredded data to validate the pipeline output.
*This enrichment is enabled by default.* And has to be explicitly disabled to allow shredding of events that won't match with the atomic event schema.
Config has a single parameter `disable`. Which was left for backward compatibility with the old behaviour. 
Config schema: https://github.com/snowplow/iglu-central/pull/1194
Events that failed by this enrichment could return: 
- `EnrichmentFailure` with identifier `shredded_validator`, in case of error converting `EnrichedEvent` to the shredded format. 
- `SchemaViolation.IgluError` refering to …
> Enforce maximum field lengths (close #517)

- .github/workflows/ci.yml
- config/config.kinesis.extended.hocon
- config/config.pubsub.extended.hocon
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Enrich.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Environment.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Run.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ConfigFile.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/io.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/io/experimental/Metadata.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ConfigFileSpec.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ParsedConfigsSpec.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/io/MetadataSpec.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/test/Aggregates.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/test/TestEnvironment.scala
This adds experimental metadata aggregation that allows exporting event-entity clusters for modelling purposes. Each predefined period of time we are sending the observed clusters to an iglu-compatible webhook.
We used to use `rc` tags to release code for testing purposes. As we now use docker images for that we only need to push these. With this change it is possible to push an image by creating a special `snapshot/` branch that will get the images pushed.
> common-fs2: Add experimental metadata aggregation sink

- config/config.kinesis.extended.hocon
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Environment.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Run.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/io.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ConfigFileSpec.scala
- modules/kinesis/src/main/resources/application.conf
- modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/KinesisRun.scala
I know that we like everything to be configurable, but I wonder if this is worth it for [these ones](https://github.com/snowplow/enrich/pull/592/files#diff-a4a13945ab9a250994b2e255a44ad844eb06dd339220a02d37ff65a46a29d3f7R91-R93), as this is only for checkpointing failures.
> enrich-kinesis: add retry mechanism for the checkpointing (close #591)

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/sqlquery/Rdbms.scala
- project/Dependencies.scala
See #626 for details of the bug.
Also, `useSSL` & `verifyServerCertificate` are deprecated in favor of new `sslMode` flag
> Common: fix mysql connection

- project/Dependencies.scala
Before bump:
```
snyk test
```
>  ✗ SQL Injection [High Severity][https://security.snyk.io/vuln/SNYK-JAVA-ORGPOSTGRESQL-2970521] in org.postgresql:postgresql@42.2.25
introduced by com.snowplowanalytics:snowplow-common-enrich_2.12@3.2.3 > org.postgresql:postgresql@42.2.25 and 8 other path(s)
>  This issue was fixed in versions: 42.2.26, 42.4.1
After bump:
```
snyk test
```
> [No high-severity vulnerabilities]
> Bump postgresql to 42.2.26

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/HttpClient.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/apirequest/HttpClientSpec.scala
See https://github.com/snowplow/enrich/issues/667
Notes on additional checks
1. this change is in [3.2.4-rc1](https://github.com/snowplow/enrich/actions/runs/2819071351)
2. I brought up a GCP pipeline and ensured enrichment version was set to 3.2.4-rc1
3. I set up a minimal `api_request_enrichment_config.json` which configures an api, one input and one output
4. I added a schema to the dev sandbox iglu server to configure the output in `api_request_enrichment_config.json`
5. I added a subscription to the good event topic so that I'd be able to pull and look at good events
6. I sent a test event to the collector of my GCP pipeline
7. I was able to see the good event coming through, enriched with the output field I had defined in `api_request_enrichment_config.json` and matching the schema …
> Common: Explicitly set Accept header

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/apirequest/ApiRequestEnrichment.scala
See: https://github.com/snowplow/enrich/issues/669
this change is in 3.2.4-rc2
1. I brought up a GCP pipeline and ensured enrichment version was set to 3.2.4-rc2
2. I set up a minimal api_request_enrichment_config.json which configures an api, one input and one output which is valid for schema version 1-0-0 (has a non-zero value for cache size)
3. I added a schema to the dev sandbox iglu server to configure the output in api_request_enrichment_config.json
4. I added a subscription to the good event topic so that I'd be able to pull and look at good events
5. I sent a test event to the collector of my GCP pipeline
6. I was able to see the good event coming through, enriched with the output field I had defined in api_request_enrichment_config.json and matching the schema I added to the iglu …
> Common: api_request_enrichment_config schema version 1-0-1 support

- project/Dependencies.scala
I took the opportunity to set the versions of all the AWS SDK v2 that we use in `enrich-kinesis` (kinesis, dynamoDb, s3, sts, cloudwatch) to the same version.
> enrich-kinesis: add STS v2 to runtime dependencies (close #643)

- .github/workflows/ci.yml
- .github/workflows/lacework.yml
- build.sbt
- config/config.kafka.extended.hocon
- config/config.kafka.minimal.hocon
- integration-tests/enrich-kafka/config/enrich-kafka.hocon
- integration-tests/enrich-kafka/config/enrichments/yauaa_enrichment_config.json
- integration-tests/enrich-kafka/config/iglu_resolver.json
- integration-tests/enrich-kafka/docker-compose.yml
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/AttributedData.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Enrich.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/Environment.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ConfigFile.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ParsedConfigs.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/io.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/EnrichSpec.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/ParsedConfigsSpec.scala
- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/test/TestEnvironment.scala
- modules/kafka/src/it/scala/com/snowplowanalytics/snowplow/enrich/kafka/test/CollectorPayloadGen.scala
- modules/kafka/src/it/scala/com/snowplowanalytics/snowplow/enrich/kafka/test/EnrichKafkaSpec.scala
- modules/kafka/src/main/resources/application.conf
- modules/kafka/src/main/scala/com.snowplowanalytics.snowplow.enrich.kafka/Main.scala
- modules/kafka/src/main/scala/com.snowplowanalytics.snowplow.enrich.kafka/Sink.scala
- modules/kafka/src/main/scala/com.snowplowanalytics.snowplow.enrich.kafka/Source.scala
- modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/Sink.scala
- modules/pubsub/src/main/scala/com/snowplowanalytics/snowplow/enrich/pubsub/Sink.scala
- modules/rabbitmq/src/main/scala/com/snowplowanalytics/snowplow/enrich/rabbitmq/Sink.scala
- project/BuildSettings.scala
- project/Dependencies.scala
Let's get the review on the initial implementation started!
This implementation is based on [fs2-kafka](https://github.com/fd4s/fs2-kafka) library. I followed the conventions of enrich-kinesis & enrich-pubsub. All of the [consumer configs](https://kafka.apache.org/documentation/#consumerconfigs) and [producer configs ](https://kafka.apache.org/documentation/#producerconfigs) can be set at runtime.
Together with stream-collector-kafka, I had a successful smoke test on localhost.
I'll focus on optimizing the throughput after passing the initial review phase. I expect our reference config to have different default values for some consumer and producer configs only after working on throughput optimization.
Next steps
-----
> Add enrich-kafka

- project/Dependencies.scala
kafka-enrich is throwing Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
> fix: add mskAuth to kafka depedencies

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentRegistry.scala
- modules/stream/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.stream/SpecHelpers.scala
Users are often confused by the “vendor” and “name” fields in the enrichment configs. There is no reason we need to validate or even use these fields, because the “schema” field already contains enough information. This commit removes the validation on “name” (I believe “vendor” is not validated) and only uses “schema” instead.
> common: do not validate enrichment names (close #767)

- modules/common-fs2/src/test/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/blackbox/adapters/SendgridAdapterSpec.scala
- modules/common/src/main/resources/reference.conf
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/SpecHelpers.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/adapters/registry/SendgridAdapterSpec.scala
Issue #797 
This PR updates the default versions of schemas for the Sendgrid adapter to version 3-0-0 instead of 2-0-0.
The new schema version contains changes in the validation of the properties (removed validation for email, IP address, increased length of an ID property). There are no structural changes in the schemas.
> Update default schema versions for the Sendgrid adapter to 3-0-0 (close #797)

- config/config.kafka.extended.hocon
- config/config.nsq.extended.hocon
- modules/cloudutils/azure/src/main/scala/com/snowplowanalytics/snowplow/enrich/azure/AzureStorageClient.scala
- modules/common-fs2/src/main/scala/com/snowplowanalytics/snowplow/enrich/common/fs2/config/io.scala
- modules/kafka/src/main/scala/com.snowplowanalytics.snowplow.enrich.kafka/Main.scala
- modules/kafka/src/test/scala/com/snowplowanalytics/snowplow/enrich/kafka/ConfigSpec.scala
- modules/nsq/src/it/scala/com/snowplowanalytics/snowplow/enrich/nsq/test/Containers.scala
- modules/nsq/src/main/scala/com/snowplowanalytics/snowplow/enrich/nsq/Main.scala
- modules/nsq/src/test/scala/com/snowplowanalytics/snowplow/enrich/nsq/ConfigSpec.scala
This PR makes azure blob storage more flexible regarding authentication methods. Now t's possible to configure multiple storage accounts (like before), but with: 
* no authentication at all. No credentials are used when accessing storage. Useful for public accounts.
* authentication using default credentials [chain](https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable). That's the method Enrich used previously for all configured accounts.
* authentication using SAS token. Token is provided in configuration and NOT generated dynamically in application. 
New configuration looks like: 
```
"azureStorage": {
"accounts": [
{ "name": "storageAccount1"},
{ "name": "storageAccount2", "auth": { "type": "default"} },
{ "name": …
```
> Add different types of authentication for azure blob storage

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/MiscEnrichments.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/miscEnrichmentSpecs.scala
Issue #851 
This PR adds the `headset` platform key to the list of recognized platform keys ahead of the iOS tracker 6 with support visionOS release.
> Add headset to the list of valid platform codes (close #851)

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentRegistry.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentRegistrySpec.scala
> Allow multiple javascript enrichments

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/CookieExtractorEnrichment.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/CookieExtractorEnrichmentSpec.scala
Previously, cookie extractor enrichment was only looking for `Cookie` header ignoring when the header has been supplied as a lower case `cookie`. This caused issues with Collector 3 that follows a case-insensitive header names.
Now, both `cookie` and `Cookie` headers are matched as containing user-agent's cookie.
1 - https://www.rfc-editor.org/rfc/rfc7230#section-3.2
> Make cookie extractor enrichment case insensitive

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/AtomicFields.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/AtomicFieldsLengthValidator.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/Failure.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/IgluUtils.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/SpecHelpers.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/AtomicFieldsSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/FailureSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/utils/IgluUtilsSpec.scala
Failure entities are started to be attached to incomplete events as derived contexts.
There are some cases that we need more information than in the bad rows to create failure entities therefore it isn't possible to create failure entities from bad rows directly. For this purpose, we created wrapper classes to attach extra information about failure entities.
> Add failure entity for incomplete events

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/utils/IgluUtils.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/EnrichmentManagerSpec.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/utils/IgluUtilsSpec.scala
At the moment, we set all self describing json to data field of incomplete event failure entity. However, failure entity has separate schema field and therefore we don't need to set all SDJ to data field. It is enough to use only data field of SDJ.
> Set data field of incomplete event failure entity to SDJ's data field only

- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/EnrichmentManager.scala
- modules/common/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/JavascriptScriptEnrichment.scala
- modules/common/src/test/scala/com.snowplowanalytics.snowplow.enrich.common/enrichments/registry/JavascriptScriptEnrichmentSpec.scala
Pass a raw list of headers as the third argument (after event and parameters) to the JavaScript enrichment function.
Example usage:
```js
function process(event, params, headers) {
for (header of headers) {
const jwt = header.match(/X-JWT:(.+)/i)
if (jwt) {
doSomething(jwt[1].trim())
}
}
}
```
> Pass request headers to the JS enrichment (close #901)

- .github/workflows/test.yml
A recent build had the following [error](https://github.com/snowplow/enrich/actions/runs/13453980079/job/37593815375#step:15:130):
```
docker-compose: command not found
```
Migrating to v2 command should solve the problem.
> Migrate docker-compose command to v2

- modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/Source.scala
- project/Dependencies.scala
This PR upgrades amazon-kinesis-client to 2.6.1 to avoid known bugs and issues as mentioned [here](https://docs.aws.amazon.com/streams/latest/dev/kcl.html)
> Upgrade amazon-kinesis-client to 2.6.1
